import pyautogui
from time import sleep

pyautogui.press('win')
sleep(1)
pyautogui.write('bloco de notas')
sleep(1)
pyautogui.press('enter')
sleep(1)
pyautogui.hotkey('alt', 'f')
pyautogui.write('o')
sleep(1)
pyautogui.press('tab')
sleep(0.5)
pyautogui.press('tab')
sleep(0.5)
pyautogui.write('50')
sleep(1)
pyautogui.press('enter')
sleep(1)
pyautogui.write('Parabens a voce \nParabens a voce ...')
sleep(1)
pyautogui.hotkey('ctrl', 's')
sleep(1)
pyautogui.write('Bot em Python')
sleep(1)
pyautogui.press('enter')