import pyautogui
from time import sleep
pyautogui.press('win')
sleep(1)
pyautogui.write('Opera Gx')
sleep(1)
pyautogui.press('enter')
sleep(2)
pyautogui.write('Youtube')
sleep(2)
pyautogui.press('enter')
sleep(1)
pyautogui.press(['tab', 'tab','tab'])
sleep(2)
pyautogui.press('teclado.png')
sleep(2)
pyautogui.write('Likotta')
sleep(2)
pyautogui.click('lupa.png')
